<?

CTemplate::draw_main_menu("default");
?>
<style>
	div.accelerator {
		float: right;
		text-align: center;
	}
	div.accelerator img {
		width: 100px;
		margin: 0px;
	}
	div#body
	{
		padding: 10px;
	}
	div#body p.contacts,
	div#body p.contacts a
	{
		font-size: 20px;
		color: orange;
		font-weight: bold;
		text-align: center;
		magin-right: auto;
		margin-left: auto;
		
		
	}
</style>

<link rel="alternate" type="application/rss+xml" title="l'actualité de Mezeval" href="feed://forum.mezeval.fr/rss.php?f=4" />

<div id="body" class="default">
	<div class="accelerator pub_google" style="width: 120px; height: 600px;">
	<script type="text/javascript"><!--
google_ad_client = "pub-2615991052842794";
/* 120x600, date de création 17/03/09 */
google_ad_slot = "2795453653";
google_ad_width = 120;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
	</div>
	<h1>Solution indépendante financée par la publicité. N'hésitez pas à cliquer dessus pour nous permettre d'améliorer et garder notre totale indépendance. Aucune information n'est fournie à des tiers, ministères inclus.<h1>
	<table style="width: 750px">
		<tr>
			<td style="width: 50%; text-align: center;">
				<img src="img/gratuit.gif"><br><br><br><br><br>
				<img src="img/collaboratif.gif">
			</td>
			<td style="width: 50%; text-align: center;">
			<div><object width="480" height="502"><param name="movie" value="http://www.dailymotion.com/swf/xbm4lh&autoPlay=1"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed src="http://www.dailymotion.com/swf/xbm4lh&autoPlay=1" type="application/x-shockwave-flash" width="480" height="502" allowfullscreen="true" allowscriptaccess="always"></embed></object><br /><b><a href="http://www.dailymotion.com/video/xbm4lh_presentation-de-mezevalfr_school">Vidéo de Pr&eacute;sentation</a> (données factices)</b></div>
			</td>
		</tr>
	</table>
	<h1>Bienvenue sur MeZéval.</h1>
	<p>
		MeZéval est un logiciel de suivi des acquis des élèves de l’école maternelle et élémentaire.
		Cet outil permet de suivre les progrès de vos élèves et d'organiser la progression de l'apprentissage.
		Intégrant les objectifs du socle commun ainsi que les propositions de progressions du ministère, il est aussi adaptable aux méthodes pédagogiques de chacun.
	</p>
	<h2>L’essentiel :</h2>
	<table>
		<tr>
			<td><img src="img/pictos_securite.jpg" style="vertical-align: text-top">
			<td>	<h3>Sécurité</h3>
<p>
		 MeZéval est un logiciel en ligne à accès sécurisé. Les données saisies appartiennent à l’établissement scolaire titulaire du contrat.
		Elles sont accessibles uniquement par les personnes munies des identifiants de connexion définis dans le contrat ou ajoutées
		par la personne habilitée de l’établissement sous contrat.
		Suivant la loi, contractuellement et conformément à l’éthique professionnelle, aucune donnée ne sera transmise à des tiers sans accord écrit de l’établissement.</p>
		<p>Suivant les recommandations de la CNIL, Mezeval a fait l’objet d’une déclaration au titre de la norme simplifiée n°29 (<a href="http://www.cnil.fr/en-savoir-plus/deliberations/deliberation/delib/170/" target="_blank">voir le texte</a>). Pour un complément d’information, rendez-vous sur le <a href="http://forum.mezeval.fr/viewtopic.php?f=4&t=36">forum</a>.
			</td>
		</tr>
		<tr>
			<td><img src="img/pictos_click.jpg"></td>
			<td>
				<h3>Mise en œuvre rapide</h3>
				<p>
					MeZéval est une application en mode hébergé, utilisable directement avec un navigateur web et une
					connexion internet. Aucun temps de perdu dans les installations, aucun risque de perte de données,
					accessible de tout poste relié à internet. Nul besoin d’un poste puissant et fonctionne quel que soit votre système d’exploitation (Windows, Linux ou MacOS).
				</p>
			</td>
		</tr>
		<tr>
			<td><img src="img/pictos_cool.jpg"></td>
			<td><h3>Prêt pour les nouveaux programmes</h3>
				<p>
					L’ensemble des socles et programmes de la rentrée 2008 sont intégrés afin de pouvoir être immédiatement opérationnels.
					Le système est adapté à la nouvelle démarche d’évaluation des acquis du socle commun. De nombreux indicateurs permettent aux professeurs des écoles d’analyser la progression de leurs élèves.
				</p>
			</td>
		</tr>
		<tr>
			<td><img src="img/pictos_compatible.jpg"></td>
			<td>
				<h3>Pérennité & compatibilité</h3>
				<p>
					Toutes les données insérées pevent être exportées dans un format standard CSV et dans un format XML facilement réutilisable. La CNIL recommande que chaque année les données soient effacées de notre base de donnée. Nous enverrons les données par emails, avant tout effacement, prévu en Août.
				</p>
			</td>
		</tr>
	</table>
	<p class="contacts"><a href="?module=contacts">Contactez-nous</a> ou <a href="?module=connexion">connectez-vous</a></p>	
</div>
