<? 
CTemplate::draw_main_menu("tarifs");
?>
<style>
	div#body
	{
		padding: 10px;
	}
</style>
<div id="body" class="default">
	<h1>Tarifs</h1>
	
	
	
	<p></p>
	
		<div class='success' style="font-size: 20px">Gratuit pour une utilisation en ligne !</div>
	
	<p>Le service comprend : </p>
	<ul>
		<li>Fourniture d’un code d’accés unique à la classe</li>
		<li>Groupes de niveaux illimités</li>
		<li>Accés aux données illimité</li>
		<li>Et tous les services inclus : accés sécurisé, données sécurisées par des sauvegardes journalières ...</li>
	</ul>
	
	<p class="alert">Si vous désirez installer Mezeval sur votre propre serveur, ou bénéficier d’une version spécifique, veuillez nous contacter.</p>
</div>
