<h1>CONDITIONS GENERALES DE LOCATION</h1>
<h2>PRÉAMBULE</h2>
L’activité de EXPERT SOLUTIONS SARL (dénommé XL ci-après) consiste en l’édition de solutions informatiques associées à l’Internet.
À ce titre XL propose à la location le logiciel MEZEVAL comme application hébergée.
Ce logiciel hébergé sur les serveurs de XL auxquels LE CLIENT accède par une liaison à distance est accessible sur abonnement annuel assorti d’une redevance.
L’utilisation du logiciel, accessible à l’adresse http://www.mezeval.fr est réservée aux établissements scolaires de l'enseignement public ou privé, quel que soit le lieu d’établissement de leur siège social, représenté par leurs salariés ou professeurs attachés dûment habilités à agir sur le site.
Le contrat est formé entre les parties au moment de l’acceptation des présentes conditions.
<h2>ARTICLE 1 : OBJET</h2>
Le présent contrat a pour objet de déterminer les conditions d’accès et d’utilisation du logiciel par LE CLIENT.
<h2>ARTICLE 2 : DURÉE</h2>
Le présent contrat prend effet à compter de son acceptation par les deux parties pour une durée de 1 (un) an sauf si précisé par les conditions particulières.
<h2>ARTICLE 3 : OBLIGATIONS DE XL</h2>
XL s’engage à mettre à disposition de l’abonné toute mise à jour du produit. XL n’assume aucune responsabilité quelle qu’elle soit quant aux informations qui sont diffusées par le biais de son logiciel, n’exerçant aucun contrôle à priori sur ces informations.
XL s’engage à mettre en place les moyens techniques permettant de garantir la confidentialité des données du client. XL s’engage à ne transmettre aucune information appartenant au CLIENT à un tiers.
XL se réserve le droit d’utiliser les données des clients pour un usage interne de sauvegarde, tests et autres activités techniques liées au développement du logiciel.
<h2>ARTICLE 4 : OBLIGATIONS DU CLIENT</h2>
LE CLIENT s’engage à n’utiliser les informations concernant les produits cités que pour ses besoins propres ou ceux de sa structure contractante et pour les seules finalités visées au présent contrat. LE CLIENT s’engage à ne pas développer ou commercialiser le logiciel objet du présent contrat ou des produits susceptibles de le concurrencer.
<h2>ARTICLE 5 : CHOIX DES MATERIELS ET LOGICIELS</h2>
Le logiciel est accessible via les protocoles HTTPS et HTML à l’adresse précisée en préambule. Certaines fonctions utilisent le format PDF et demandent un logiciel tiers librement utilisable.
Les navigateurs supportées sont Mozilla Firefox, Apple Safari 2 et 3 et Microsoft Internet Explorer 6 et 7.
XL ne fournit pas la connexion internet et ne peut en aucun cas être tenu responsable de problèmes liés à cette connexion.
Il appartient au CLIENT de s’assurer que les matériels dont il dispose, notamment ses logiciels d’interrogations (navigateurs) ou ses moyens de connexion, sont susceptibles d’utiliser avec toute l’efficacité requise le logiciel.
<h2>ARTICLE 6 : PROCÉDURE D’ACCÈS AU LOGICIEL</h2>
<h3>6-1 : Identifiant et mot de passe</h3>
Le logiciel est accessible par le biais d’une connexion à distance grâce à un identifiant et un mot de passe agréés par XL. Lors de la conclusion du contrat le client doit fournir à XL la liste des adresses courriel des utilisateurs habilités à utiliser le logiciel. XL enverra par courrier électronique à chaque adresse fournie un mot de passe d’au moins 6 caractères alphanumériques, l’adresse éléctronique faisant office d’identifiant de connexion. Un contrôle d’unicité est effectué par le système. Pour des raisons de sécurité et de confidentialité, seule la combinaison de ces deux codes permet au client d’accéder au logiciel. L’identifiant et le mot de passe valent preuve de l’identité du client et l’engagent sur toute utilisation faite par son intermédiaire. Il auront valeur de signature électronique au sens de l’article 1316-4 du Code civil.
LE CLIENT est le responsable entier et exclusif de son identifiant et de son mot de passe. Il supportera seul les conséquences qui pourraient résulter de l’utilisation par des tiers qui auraient eu connaissance de ceux-ci. En cas de perte de son mot de passe, LE CLIENT prévient XL qui créera un nouveau mot de passe et le lui enverra par courrier électronique après avoir effectué un contrôle sur ses données personnelles.
<h3>6-2 : mode opératoire et preuve</h3>
Une fois l’identification du client vérifiée par le biais de son identifiant et de son mot de passe, un décompte d’utilisation du logiciel est déclenché. Les parties conviennent que l’utilisation du compte du CLIENT par lui-même ou par un tiers fera preuve entre elles de l’acceptation de la transaction, quel qu’en soit le montant et quel que soit le support utilisé.
Ces modalités de preuve constituent une présomption irréfragable. Les systèmes d’enregistrement de XL sont considérés comme valant preuve de la date et de la durée de l’utilisation. L’ensemble des éléments relatifs à l’utilisation du compte seront conservés et archivés par XL. XL pourra se prévaloir, notamment à des fins probatoires, de tout acte, fichier, enregistrement, rapport de suivi, statistiques sur tous supports dont le support informatique établi, reçu ou conservé directement ou indirectement par XL dans une base de données.
<h2>ARTICLE 7 : ASSISTANCE</h2>
L’assistance se fera en ligne par l’intermédiaire d’un courrier électronique. L’abonné pourra faire une demande d’assistance à XL à l’adresse électronique suivante :  tech@mezeval.fr et par téléphone au numéro suivant 05 56 74 26 90. XL lui répondra par courrier électronique dans les meilleurs délais.
<h2>ARTICLE 8 : PRIX</h2>
<h3>8-1 : Abonnement annuel</h3>
Le prix de l’abonnement annuel au service proposé par XL est défini par les conditions particulières, suivant les options choisies. Le prix de l’abonnement ne comprend pas le coût des télécommunications et d’accès à Internet permettant l’utilisation du logiciel qui restent à la charge du client.
<h3>8-2 : Paiement</h3>
Les règlements peuvent se faire par chèque bancaire ou tout moyen approuvé par les deux parties à la commande pour la première période et en début de période pour les périodes suivantes.
<h3>8-3 : Retard ou défaut de paiement</h3>
 Tout retard dans le paiement de la redevance fera courir des intérêts au taux moyen en vigueur à la date d’exigibilité. Ces derniers courent jusqu’à paiement intégral sur la totalité des sommes dues.
<h2>ARTICLE 9 : PROPRIÉTÉ</h2>
Le présent contrat ne confère au client aucun droit de propriété intellectuelle sur le logiciel, qui demeure la propriété entière et exclusive de XL. LE CLIENT s’oblige à respecter les mentions de propriété figurant sur le logiciel, les support et la documentation.
9-1 : Reproduction - adaptation</h3>
LE CLIENT s’interdit formellement de reproduire de façon permanente ou provisoire le logiciel en tout ou partie, par tout moyen et sous toute forme, y compris à l’occasion du chargement, de l’affichage, de l’exécution ou du stockage du logiciel. LE CLIENT s’interdit de traduire, d’adapter, d’arranger ou de modifier le logiciel, de l’exporter, de le fusionner avec d’autres applications informatiques.
9-2 : Corrections d’erreurs</h3>
XL se réserve expressément le droit exclusif d’intervenir sur le logiciel pour lui permettre d’être utilisé conformément à sa destination et notamment pour en corriger les erreurs. LE CLIENT s’interdit donc formellement d’intervenir ou de faire intervenir un tiers sur le logiciel. La mise à disposition du logiciel ne saurait être considérée comme une cession au sens du Code de la propriété intellectuelle d’un quelconque droit de propriété intellectuelle au bénéfice du client.
<h2>ARTICLE 10 : RESPONSABILITÉ</h2>
XL est soumis à une obligation de moyen, à l’exclusion de toute autre. Elle garantit la conformité du logiciel aux spécifications. LE CLIENT assume toutes les responsabilités autres que celle de conformité du logiciel aux spécifications et notamment celles qui concernent :
-          l’adéquation du logiciel à ses besoins
-          l’exploitation du logiciel
-          la qualification et la compétence de son personnel
LE CLIENT reconnaît expressément avoir reçu de XL toutes les informations nécessaires lui permettant d’apprécier l’adéquation du progiciel à ses besoins et de prendre toutes les précautions utiles pour sa mise en œuvre et son exploitation. XL ne sera en aucun cas tenue de réparer d’éventuels dommages directs ou indirects. XL ne pourra être tenue pour responsable de la qualité de la liaison Internet du client.
En aucun cas, XL ne pourra être tenue responsable de dommages indirects tels que la perte de marché, le préjudice commercial, la perte de clientèle, le trouble commercial quelconque, la perte de bénéfice, la perte de l’image de marque ou de toute action en concurrence estimée déloyale.
 LE CLIENT sera seul responsable de l’utilisation du progiciel. Lors du transfert par moyen de télécommunication ou par tout autres moyens, aucune responsabilité ne pourra être retenue contre XL en cas d’altération des informations ou des données durant le transfert.
XL ne saurait être tenue responsable de dommage résultant de la perte, de l’altération ou de toute utilisation frauduleuse de données, de la transmission accidentelle de virus ou autres éléments nuisibles, de l’attitude ou comportement d’un tiers, de la non-conclusion d’une vente. XL ne peut être tenue responsable d’éventuels disfonctionnements sur le poste du CLIENT à la suite de l’utilisation du logiciel.
<h2>ARTICLE 11 : CONTREFAÇONS</h2>
XL garantit qu’elle est titulaire des droits de propriété intellectuelle lui permettant de conclure le présent contrat et que le logiciel n’est pas susceptible de porter atteinte aux droits de tiers. Elle garantit de même que le logiciel est entièrement original et n’est constitutif en tout ou en partie ni de contrefaçon, ni de concurrence déloyale. LE CLIENT s’engage à signaler immédiatement à XL toute contrefaçon du logiciel dont il aurait connaissance, XL étant alors libre de prendre les mesures qu’elle jugera appropriées.
<h2>ARTICLE 12 – RÉSILIATION</h2>
En cas de manquement de l’une des parties à ses obligations telles que stipulées ci-dessus, les présentes pourront être résiliées par l’autre partie 15 (quinze) jours après la réception d’une lettre recommandée avec avis de réception. Cette lettre sera motivée et indiquera la ou les défaillances constatées et restées sans effet après ce délai. Au cas où des informations diffusées par le biais du logiciel seraient manifestement incompatibles avec l’image de XL, ce dernier pourra résilier le présent contrat 15 (quinze) jours après réception par LE CLIENT d’une lettre recommandée avec accusé de réception motivée, l’informant des incompatibilités constatées.
<h2>ARTICLE 13 – ARRÊT DU SERVICE</h2>
En cas d’arrêt définitif du service à l’initiative d’XL, XL s’engage à fournir l’ensemble des données, les sources du logiciel et les instruction permettant de faire fontionner l’application.
<h2>ARTICLE 14 : INTÉGRALITÉ</h2>
Le présent contrat représente la totalité et l’intégralité de l’entente intervenue entre les parties.
 Il ne pourra être modifié que par un avenant convenu d’un commun accord.
<h2>ARTICLE 15 : LOI APPLICABLE ET TRIBUNAL COMPÉTENT</h2>
Le présent contrat est soumis à la loi Française. Tout différent lié à l’interprétation, l’exécution ou la validité du présent contrat sera soumise à la compétence exclusive du Tribunal de Commerce de Bordeaux, France.
<h2>ARTICLE 16 : INCESSIBILITÉ</h2>
 Il est expressément convenu que le présent contrat ne pourra être cédé à un tiers par LE CLIENT, sauf accord préalable et écrit de XL.
<h2>ARTICLE 16 : ÉLECTION DE DOMICILE</h2>
Les parties élisent domicile aux adresses définies dans les conditions particulières.

BORDEAUX LE PREMIER SEPTEMBRE DEUX MILLE HUIT (01/09/2008)
