<h1>CONDITIONS GENERALES D'UTILISATION DE WWW.MEZEVAL.FR</h1>

<h2>PRÉAMBULE</h2>

<p>L’activité de EXPERT SOLUTIONS SARL (dénommée XL ci-après) consiste en l’édition de solutions informatiques associées à l’Internet.
À ce titre XL propose en accès libre le logiciel MEZEVAL comme application hébergée à toute personne (dénommé L'USAGER).
Ce logiciel hébergé sur les serveurs de XL auxquels L'USAGER accède par une liaison à distance est accessible librement à l'adresse https://www.mezeval.fr.
Le contrat est formé entre les parties au moment de l’acceptation des présentes conditions.</p>

<h2>ARTICLE 1 : OBJET</h2>
<p>Le présent contrat a pour objet de déterminer les conditions d’accès et d’utilisation du logiciel par L'USAGER.</p>

<h2>ARTICLE 2 : DURÉE</h2>
	<p>
		Le présent contrat prend effet à compter de son acceptation par les deux parties pour une durée d'1 (un) an.
	</p>

<h2>ARTICLE 3 : OBLIGATIONS DE XL</h2>

<p>XL a effectué une déclaration (n°1343911) de fichiers auprès de la Commission Nationale de l'Informatique et des Libertés (dénommée CNIL ci-après), au titre de la norme simplifiée de référence NS-29 concernant les fichiers de "Gestion des écoles et des ets secondaires publics et privés".<p>

<p>XL n’assume aucune responsabilité quelle qu’elle soit quant aux informations qui sont diffusées par le biais de son logiciel, n’exerçant aucun contrôle à priori sur ces informations.
XL s’engage à mettre en place les moyens techniques permettant de garantir la confidentialité des données de L’USAGER. XL s’engage à ne transmettre aucune information appartenant à L'USAGER à un tiers.
XL se réserve le droit d’utiliser les données de L'USAGER pour un usage interne de sauvegarde, tests et autres activités techniques liés au développement du logiciel.</p>

<p>XL s'engage à fournir à l’usager un document d’information auprès des parents d’élèves sur leurs droits concernant l'usage du logiciel.</p>

<h2>ARTICLE 4 : OBLIGATIONS DE L’USAGER</h2>

<p>L’USAGER s’engage à n’utiliser les informations concernant les produits cités que pour ses besoins propres et pour les seules finalités visées au présent contrat.</p>

<p>L’USAGER s'engage à informer les parents des élèves sur l'usage du logiciel, conformément aux disposition de la norme simplifiée NS-29 de la CNIL, dans le cas ou il utilise dans le logiciel les noms et prénoms de ces élèves.</p>

<p>L’USAGER s'engage à avertir XL si il constate une possibilité d'accéder à des données qui ne sont pas les siennes.</p>

<h2>ARTICLE 5 : CHOIX DES MATERIELS ET LOGICIELS</h2>
<p>Le logiciel est accessible via les protocoles HTTPS et HTML à l’adresse précisée en préambule. Certaines fonctions utilisent le format PDF et demandent un logiciel tiers librement utilisable (ex. : Adobe Acrobat).
Les navigateurs supportés sont Mozilla Firefox, Apple Safari 2 et 3 et Microsoft Internet Explorer 6, 7 et 8.
XL ne fournit pas la connexion internet et ne peut en aucun cas être tenu responsable de problèmes liés à cette connexion.
Il appartient à L’USAGER de s’assurer que les matériels dont il dispose, notamment ses logiciels d’interrogations (navigateurs) ou ses moyens de connexion, sont susceptibles d’utiliser avec toute l’efficacité requise le logiciel.</p>

<h2>ARTICLE 6 : PROCÉDURE D’ACCÈS AU LOGICIEL</h2>

<h3>6-1 : Identifiant et mot de passe</h3>
<p>Le logiciel est accessible par le biais d’une connexion à distance grâce à un identifiant et un mot de passe agréés par XL. Lors de l'ouverture d'un compte utilisateur, L’USAGER doit fournir à XL une adresse email valide, seulement accessible par L’USAGER. XL enverra par courrier électronique à cette adresse un mot de passe d’au moins 6 caractères alphanumériques, l’adresse électronique faisant office d’identifiant de connexion. Un contrôle d’unicité est effectué par le système. Pour des raisons de sécurité et de confidentialité, seule la combinaison de ces deux codes permet à L'USAGER d’accéder au logiciel. L’identifiant et le mot de passe valent preuve de l’identité de L’USAGER et l’engagent sur toute utilisation faite par son intermédiaire. Ils auront valeur de signature électronique au sens de l’article 1316-4 du Code civil.
L’USAGER est le responsable entier et exclusif de son identifiant et de son mot de passe. Il supportera seul les conséquences qui pourraient résulter de l’utilisation par des tiers qui auraient eu connaissance de ceux-ci. En cas de perte de son mot de passe, L’USAGER prévient XL qui créera un nouveau mot de passe et le lui enverra par courrier électronique après avoir effectué un contrôle sur ses données personnelles.</p>

<h3>6-2 : mode opératoire et preuve</h3>
<p>Une fois l’identification de L’USAGER vérifiée par le biais de son identifiant et de son mot de passe, un décompte d’utilisation du logiciel est déclenché. Ces modalités de preuve constituent une présomption irréfragable. Les systèmes d’enregistrement de XL sont considérés comme valant preuve de la date et de la durée de l’utilisation. L’ensemble des éléments relatifs à l’utilisation du compte seront conservés et archivés par XL. XL pourra se prévaloir, notamment à des fins probatoires, de tout acte, fichier, enregistrement, rapport de suivi, statistiques sur tous supports dont le support informatique établi, reçu ou conservé directement ou indirectement par XL dans une base de données.</p>

<h2>ARTICLE 7 : ASSISTANCE</h2>
<p>L’assistance s'effectue en ligne par l’intermédiaire d’un forum électronique disponible à l'adresse suivante : http://forum.mezeval.fr. L'USAGER pourra cependant faire une demande d’assistance à XL à l’adresse électronique suivante :  tech@mezeval.fr. XL lui répondra par courrier électronique dans les meilleurs délais.</p>

<h2>ARTICLE 8 : PRIX</h2>
<p>L'utilisation de l'application est libre dans le temps et gratuite à partir de la création d'un identifiant. XL se réserve le droit d'ajouter des services libres. Xl se réserve le droit de rendre payant toute ou partie des fonctions du logiciel, dans ce cas, et pour les fonctionnalités existantes, XL devra en faire publicité sur le site web de mezeval 3 mois avant la mis en application.</p>

<h2>ARTICLE 9 : PROPRIÉTÉ</h2>

<p>Le présent contrat ne confère à L'USAGER aucun droit de propriété intellectuelle sur le logiciel, qui demeure la propriété entière et exclusive de XL. L'USAGER s’oblige à respecter les mentions de propriété figurant sur le logiciel, les support et la documentation.</p>

<h3>9-1 : Reproduction - adaptation</h3>

<p>L'USAGER s’interdit formellement de reproduire de façon permanente ou provisoire le logiciel en tout ou partie, par tout moyen et sous toute forme, y compris à l’occasion du chargement, de l’affichage, de l’exécution ou du stockage du logiciel. L'USAGER s’interdit de traduire, d’adapter, d’arranger ou de modifier le logiciel, de l’exporter, de le fusionner avec d’autres applications informatiques.</p>

<h3>9-2 : Corrections d’erreurs</h3>

<p>XL se réserve expressément le droit exclusif d’intervenir sur le logiciel pour lui permettre d’être utilisé conformément à sa destination et notamment pour en corriger les erreurs. L'USAGER s’interdit donc formellement d’intervenir ou de faire intervenir un tiers sur le logiciel. La mise à disposition du logiciel ne saurait être considérée comme une cession au sens du Code de la propriété intellectuelle d’un quelconque droit de propriété intellectuelle au bénéfice de L'USAGER.</p>

<h2>ARTICLE 10 : RESPONSABILITÉ</h2>
<p>XL est soumis à une obligation de moyen, à l’exclusion de toute autre. Elle garantit la conformité du logiciel aux spécifications. L'USAGER assume toutes les responsabilités autres que celle de conformité du logiciel aux spécifications et notamment celles qui concernent :
<ul>
	<li>l’adéquation du logiciel à ses besoins
	<li>l’exploitation du logiciel
	<li>la qualification et la compétence de son personnel
</ul>
L'USAGER reconnaît expressément avoir reçu de XL toutes les informations nécessaires lui permettant d’apprécier l’adéquation du progiciel à ses besoins et de prendre toutes les précautions utiles pour sa mise en œuvre et son exploitation. XL ne sera en aucun cas tenu de réparer d’éventuels dommages directs ou indirects. XL ne pourra être tenu pour responsable de la qualité de la liaison internet de L'USAGER.
En aucun cas, XL ne pourra être tenu responsable de dommages indirects tels que la perte de marché, le préjudice commercial, la perte de clientèle, le trouble commercial quelconque, la perte de bénéfice, la perte de l’image de marque ou de toute action en concurrence estimée déloyale.
 L'USAGER sera seul responsable de l’utilisation du progiciel. Lors du transfert par moyen de télécommunication ou par tout autre moyen, aucune responsabilité ne pourra être retenue contre XL en cas d’altération des informations ou des données durant le transfert.
XL ne saurait être tenu responsable de dommage résultant de la perte, de l’altération ou de toute utilisation frauduleuse de données, de la transmission accidentelle de virus ou autres éléments nuisibles, de l’attitude ou comportement d’un tiers, de la non-conclusion d’une vente. XL ne peut être tenue responsable d’éventuels dysfonctionnements sur le poste de L'USAGER à la suite de l’utilisation du logiciel.</p>

<h2>ARTICLE 11 : CONTREFAÇONS</h2>
<p>XL garantit qu’elle est titulaire des droits de propriété intellectuelle lui permettant de conclure le présent contrat et que le logiciel n’est pas susceptible de porter atteinte aux droits de tiers. Elle garantit de même que le logiciel est entièrement original et n’est constitutif en tout ou en partie ni de contrefaçon, ni de concurrence déloyale. L'USAGER s’engage à signaler immédiatement à XL toute contrefaçon du logiciel dont il aurait connaissance, XL étant alors libre de prendre les mesures qu’elle jugera appropriées.</p>

<h2>ARTICLE 12 – RÉSILIATION</h2>

<h3>À l'initialtive de L'USAGER</h3>
<p>L'USAGER peut arrêter à tout instant d'utiliser l'application. Il sera de son ressort de supprimer les données le concernant dans l'application. Il pourra pour se faire utiliser la fonction de suppression de compte.</p>

<h3>À l'initialtive d'XL</h3>

<p>XL pourra supprimer un compte utilisateur en cas de manquement aux obligations de confidentialité. XL enverra un courrier électronique 15 (quinze) jours avant la date de suppression et une relance 7 (sept) jours avant. Dans ce délai de 15 jours, L'USAGER pourra réclamer une motivation ainsi que la restitution complète des données.
</p>
	
<h2>ARTICLE 13 – ARRÊT DU SERVICE</h2>
<P>En cas d’arrêt définitif du service à l’initiative d’XL, XL s’engage à fournir l’ensemble des données, les sources du logiciel et les instruction permettant de faire fonctionner l’application.</p>

<h2>ARTICLE 14 : INTÉGRALITÉ</h2>
<p>Le présent contrat représente la totalité et l’intégralité de l’entente intervenue entre les parties.
 Il ne pourra être modifié que par un avenant convenu d’un commun accord.</p>

<h2>ARTICLE 15 : LOI APPLICABLE ET TRIBUNAL COMPÉTENT</h2>
<p>Le présent contrat est soumis à la loi Française. Tout différent lié à l’interprétation, l’exécution ou la validité du présent contrat sera soumise à la compétence exclusive du Tribunal de Commerce de La Rochelle, France.</p>

<h2>ARTICLE 16 : ÉLECTION DE DOMICILE</h2>
<p>Les parties élisent domicile aux adresses définies dans les conditions particulières.</p>

<p>LA ROCHELLE LE PREMIER AVRIL DEUX MILLE NEUF (01/04/2009)</p>
